---
abstract: 'Gets the boolean representative of a string'
author:
  - 'Andreas Hernitscheck <ahernit@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-BooleanSimple
requires:
  Exporter: '0'
  boolean: '0'
  vars: '0'
version: '0.023'
